# Generated by Django 2.1 on 2018-09-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0002_apistep_apistep'),
    ]

    operations = [
        migrations.AddField(
            model_name='apistep',
            name='apiresponse',
            field=models.CharField(max_length=5000, null=True, verbose_name='返回值值'),
        ),
    ]
