# Generated by Django 2.1 on 2018-09-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0004_auto_20180912_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='apimethod',
            field=models.CharField(choices=[('0', 'get'), ('1', 'post'), ('2', 'put'), ('3', 'delete'), ('4', 'patch')], default='0', max_length=200, verbose_name='请求方法'),
        ),
    ]
